# Generated by Django 3.2.4 on 2021-11-12 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Normal user')], default=2, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('published_date', models.DateField(null=True)),
                ('created_at', models.DateField(default=datetime.date(2021, 11, 12))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.author')),
            ],
        ),
    ]
