# Generated by Django 3.2.4 on 2021-11-26 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20211125_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genere',
            name='number',
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 11, 26)),
        ),
        migrations.CreateModel(
            name='GenegeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_book', models.SmallIntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.book')),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.genere')),
            ],
        ),
    ]
