# Generated by Django 3.2.4 on 2021-11-30 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20211126_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Published'), (2, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 11, 30)),
        ),
    ]
