# Generated by Django 3.2.4 on 2021-12-03 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20211130_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 12, 3)),
        ),
    ]
